### ISSUE TITLE
Hardcore questing mod & your mod together crash

### ISSUE THREAD

**Issue by TheeMrCheeky** [Globox1997/LevelZ#128]
When creating a new task in quest book it leads to game crashing only when your mod is paired with it

**Comment by kirderf1** [comment]
Related issues: https://github.com/lorddusk/HQM/issues/657, https://github.com/AHilyard/LegendaryTooltips/issues/24. Crash appear to happen at https://github.com/Globox1997/LevelZ/blob/fb01405bcfcf21721ea95dbe93140ac72257df71/src/main/java/net/levelz/mixin/item/ItemStackClientMixin.java#L68 where `tooltipAddition` is null, causing a crash.

**Comment by Globox1997** [comment]
Thanks for reporting this, I wonder how the list can be null, maybe Lists.newArrayList(); can be null out of prod env.
Fixed with null check [https://github.com/Globox1997/LevelZ/commit/7062eff0518db0f4b990c81a438272e76dca3689](https://github.com/Globox1997/LevelZ/commit/7062eff0518db0f4b990c81a438272e76dca3689)

**Comment by kirderf1** [comment]
Checked back on this after getting a new reported crash, but with levelZ 1.3.3.
First, the null check fix is faulty because it uses `&` instead of `&&`, causing `this.tooltipAddition.isEmpty()` to be evaluated regardless of if `tooltipAddition` is null.
Second, I have a good guess on the root of the problem: The air item should have id 0. If the tooltip mixin function were to be called for an item stack for the first time with the air item, `this.itemId != itemId` would be false (because `this.itemId` would initialize as 0), causing `tooltipAddition` to never be initialized.
If this really is the case,
- LevelZ could fix this by fixing the null check or by accounting for the item potentially being air/item id potentially being 0.
- Mods with compatibility issues could avoid this crash by avoiding to get the tooltip of an empty itemstack.
