### ISSUE TITLE
Incompatible with HT's TreeChop

### ISSUE THREAD

**Issue by TheKuwagata** [Globox1997/LevelZ#191]
If i chop tree with locked axe i chop it down with TreeChop mod. Is it possible to fix this problem?
https://www.curseforge.com/minecraft/mc-mods/treechop/files/4013577

**Comment by Globox1997** [comment]
Mh I see the issue

**Comment by hammertater** [comment]
The mixin is causing crashes after a TreeChop update, see https://github.com/hammertater/treechop/issues/215

Any classes that aren't in the ht.treechop.api package are potentially unstable, so instead of using mixins, you could prevent TreeChop from detecting trees using events. See https://github.com/hammertater/treechop/blob/main/fabric/src/main/java/ht/treechop/api/TreeChopEvents.java

Specifically, register a listener for the DETECT_TREE event that returns null whenever the player shouldn't be able to chop things. This should also stop TreeChop from showing an on-screen chop indicator, showing tree info in WAILA mods, etc., and will also stop TreeChop from running expensive tree detection checks

**Comment by xR4YM0ND** [comment]
Fixed in newest version for 1.20.1
