### ISSUE TITLE
Crash with Go Fish Mod

### ISSUE THREAD

**Issue by sweetsosweet** [Globox1997/LevelZ#26]
I guess these two mods are not compatible? Both load on their own.

Here's the mod test list:

- cloth-api-2.0.54
- cloth-config-5.0.38-fabric
- fabric-api-0.39.2+1.17
- go-fish-1.3.0-beta-1.17.1
- levelz-1.0.7

(also tried later with fabric-api-0.40.1+1.17)

Here's my log: [https://gist.github.com/sweetsosweet/d22154f3dd934b79279323fe6a973295](https://gist.github.com/sweetsosweet/d22154f3dd934b79279323fe6a973295)

**Comment by Globox1997** [comment]
Yes, for some reason Draylar uses an Overwrite inside the FishingRodItem class on the use method which makes it incompatible with all other mods which try to inject stuff into the same method. It doesn't need to be an Overwrite but that is not in my hands.
Here:[https://github.com/Draylar/go-fish/blob/master/src/main/java/draylar/gofish/mixin/FishingRodPropertyMixin.java](https://github.com/Draylar/go-fish/blob/master/src/main/java/draylar/gofish/mixin/FishingRodPropertyMixin.java)

**Comment by sweetsosweet** [comment]
Ok, thank you, I'll bring this issue to Go Fish.

**Comment by Globox1997** [comment]
Since Draylar doesn't look like he is gonna change anything in this method (which would be simple ;) ), I removed the mixin when this mod is loaded with [https://github.com/Globox1997/LevelZ/commit/3c829c742042b06b1edb15890016c1d48e901a29](https://github.com/Globox1997/LevelZ/commit/3c829c742042b06b1edb15890016c1d48e901a29)
