### ISSUE TITLE
TOO MANY LEVELZ XP ORBS ARE BLOCKING PLAYER"S VIEW

### ISSUE THREAD

**Issue by Thelegendking** [Globox1997/LevelZ#321]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.23

### Mod Version

1.4.11

### Describe the Issue

![2023-10-29_16 40 11](https://github.com/Globox1997/LevelZ/assets/89863459/b42438f1-7455-45b7-a904-e543641038e2)
![2023-10-29_16 40 09](https://github.com/Globox1997/LevelZ/assets/89863459/8cd6a6f1-18ec-4613-bec7-2ede47c64c9c)
![2023-10-29_16 39 49](https://github.com/Globox1997/LevelZ/assets/89863459/187c786a-d3ae-4c2f-9322-0f45acc0af0d)

### latest.log

s

### Do you use any other mods except the required ones?

Farmer's delight, Xaero minimap, and Jade

**Comment by ProducerMZ** [comment]
![2023-12-XP_Err3](https://github.com/Globox1997/LevelZ/assets/123271596/3efb9f16-74ff-4515-9708-53aa783881bc)
![2023-12-20_XP_err1](https://github.com/Globox1997/LevelZ/assets/123271596/ed405223-2ec3-4f3c-90ca-ce80424feee7)
![2023-12-20_XP_err2](https://github.com/Globox1997/LevelZ/assets/123271596/f29a7510-72eb-4e66-9a4a-0fcd7076d563)
This issue is constantly lagging my world. Here's the only solution I've found:
Under the "Experience settings" tab in the LevelZ config, turn the "Use independent XP" setting to "No". This eliminates the blue XP altogether removing the overflow issue, but you won't have your levels automatically applied anymore. You'll have to constantly check the LevelZ Skills page to see if your present XP is more than the XP required to level up, then click the top most + button to apply the level(s) and get the points to distribute. 
It's less convenient, for sure, but it works.
Hope this helps.

**Comment by Globox1997** [comment]
Update to latest version
