### ISSUE TITLE
Incompatiblity with "The Guild" mod: Profession duplication

### ISSUE THREAD

**Issue by Fulmineo64** [Globox1997/LevelZ#37]
Hi Globox_Z!

This mod is very cool, but it is full of incompatibilities!

I'm writing to you for an issue with my latest release: The Guild mod.
When LevelZ is installed the Quests Professions of the players double every time the world is loaded!

I don't even know why it happens, but If you need help figuring it out I'm here!

Also here's the original issue on my repo thoroughly explained by Anhelm:
https://github.com/Fulmineo64/Guild/issues/7

Anhelm experienced it on multiplayer, but it also happens in singleplayer.

If you need me, you can find me on my Discord:
https://discord.gg/G8s2q4wMnt

Thank you!

**Comment by Globox1997** [comment]
Yes it can have a lot of incompats cause I use a lot of mixins but most of them are Injections which makes it compatible with other mods except they use redirects or overwrites (which is basically not a good solution).
Not sure what could cause this.

**Comment by OxcydePlays** [comment]
Hi, I got another crashlog about this issue: https://pastebin.com/nuRKTASx

This was after updating to both LevelZ 1.0.12 and The Guild 0.3.1 (@Fulmineo64 sadly the workaround didn't work for me)

P.S.: I seem to still be getting the Luck enchantment almost constantly, probably coming from the incompatibility with MCDArtifacts. I don't mind it though since I'm no longer getting the Bad Luck debuff that came along with it back then.

**Comment by Globox1997** [comment]
I will look into it

**Comment by Globox1997** [comment]
Okay found the issue and fixed it with [https://github.com/Globox1997/LevelZ/commit/156886ad64f6d83ff06aa5011d322578b920ab8e](https://github.com/Globox1997/LevelZ/commit/156886ad64f6d83ff06aa5011d322578b920ab8e)
But there is a reason why in the reading method information gets set and not just added :)
