### ISSUE TITLE
1.18 Crash 'LevelZ failed injection check'

### ISSUE THREAD

**Issue by kaidejager** [Globox1997/LevelZ#60]
I'm sure it's some incompatibility but not Origins

[latest.log](https://github.com/Globox1997/LevelZ/files/7652648/latest.log)

**Comment by Globox1997** [comment]
Can you test this for me? you have to unzip the file
[levelz-1.1.2.zip](https://github.com/Globox1997/LevelZ/files/7655662/levelz-1.1.2.zip)

**Comment by kaidejager** [comment]
works without TaxFreeLevels but heres the crash with it, just in case.
[latest.log](https://github.com/Globox1997/LevelZ/files/7655796/latest.log)

**Comment by Globox1997** [comment]
Yea this got already reported, levelz already has a similar function for the anvil xp cost

**Comment by kaidejager** [comment]
ok, I opened an issue on their github too. Thanks for the quick fix.

**Comment by Fourmisain** [comment]
Hey, Tax Free Level dev here!

I see that this has been reported in https://github.com/Globox1997/LevelZ/issues/22 back in september even, I had no idea!

It is definitely possible to make both mods compatible, though probably not without changes on both sides.

The question that should be asked first is though if that's actually desirable.

From what I can see, LevelZ adds scaling to the anvil's level cost based off its smithing skill, so the higher the skill, the lower the cost.
Tax Free Levels changes the anvil level cost into an XP cost which is independent of the player's current level.
Player level 3, player level 300, doesn't matter, you pay the same amount of XP (depending on the anvil level cost).

I do think that it makes sense to make the mods compatible concept wise.

That said, I've never been too sure about Tax Free Level's anvil handling, because it (currently) always bases the cost off of player level 0, so if you're level 30 and you pay 5 levels, it costs the XP needed to get from level **0** to 5 instead of 25 to 30, which makes mathematical sense but also isn't a whole lot.

If you add additional smithing level scaling on top of that, this does (currently) seems like too much at once - for low player levels at least.

That all being said, 
I think it still make sense to at least allow Tax Free Level's enchantment level handling, which IMHO is where it really shines.
I'm not sure what exactly LevelZ does to the enchanting table, but it at least looks like there's no direct conflict in code or in design there, so I could make Tax Free Levels compatible by simply disabling its anvil logic when LevelZ is present.

Toughts, objections?

Btw, while looking at the code I found a small bug:

https://github.com/Globox1997/LevelZ/blob/d22a14c0aca37fed4f87a09ce926af5b87508d59/src/main/java/net/levelz/mixin/misc/AnvilScreenHandlerMixin.java#L49-L53

According to the config comment, `smithingToolChance` is the chance for no tool damage and it's used as such too, but I think this one here should be `smithingAnvilChance` since its comment says "Chance of no xp usage on anvil at max lvl" and it's currently unused.

**Comment by Globox1997** [comment]
Hey Fourmisain,
Thanks for reporting the "bug" :D Fixed with [https://github.com/Globox1997/LevelZ/commit/f95420414ccab4ec3d8a64c873c68bce53342958](https://github.com/Globox1997/LevelZ/commit/f95420414ccab4ec3d8a64c873c68bce53342958)
Also added require annotation with the same commit to make it compatible with tax free levels.
This can be closed then :)

**Comment by Fourmisain** [comment]
> Also added require annotation with the same commit to make it compatible with tax free levels.

Aw, you shouldn't have 😄

I'm currently restructuring my mod so that it's easier to make other mods compatible with it. Is it okay if I create a Pull Request to make LevelZ compatible without disabling your mixin? (Because that's what `require = 0` will do)

I might think about how to do this for a few more days.
The current plan is to replace the `@Redirect` with a `@ModifyArg` - only issue being that the method won't have the `playerEntity` parameter, so that needs to be "captured" e.g. via an `@Inject` and stored into a new field.
For comparison, this is how it looks on my end [before](https://github.com/Fourmisain/TaxFreeLevels/blob/e7a6e8baaee88ec3707777cfaa36c2ae287adda2/src/main/java/fourmisain/taxfreelevels/mixin/AnvilScreenHandlerMixin.java#L23-L32) and this is [after](https://github.com/Fourmisain/TaxFreeLevels/blob/c93bd91072966613f7a826bf4207fa04702e36de/src/main/java/io/github/fourmisain/taxfreelevels/mixin/FlattenAnvilCostMixin.java#L21-L40) (WIP) - it's a bit ugly, which is why I wanna look for alternatives.

**Comment by Globox1997** [comment]
if you add require = 0 too and set the priority lower (which means a higher number) only levelz redirect should get applied :)

**Comment by Fourmisain** [comment]
I've actually already [disabled that mixin](https://github.com/Fourmisain/TaxFreeLevels/blob/c93bd91072966613f7a826bf4207fa04702e36de/src/main/java/io/github/fourmisain/taxfreelevels/MixinConfig.java#L47-L50) when LevelZ is found, though proper compatibility would be nice.

You wouldn't have to lift a finger, except to press "merge pull request", it's fine if you don't want to though. 😄

Btw, the reason I don't use `require = 0` is because it will make mixins (more or less) silently fail, but I much prefer knowing about mod conflicts so that I can resolve them.

**Comment by Globox1997** [comment]
What will your PR do?^^
Silent fails don't sound good but I think for a redirect it is okay :D

**Comment by Fourmisain** [comment]
> What will your PR do?^^

As mentioned, I wanted to replace the `@Redirect` with a `@ModifyArg` and add a few other lines to make it work.
Only one mod can `@Redirect` a method, but `@ModifyArg` can be used by as many mods as one wants.

> Silent fails don't sound good but I think for a redirect it is okay :D

Yeah, it depends, some things aren't so bad if they fail, like your redirect only adds a 10% chance to have no anvil cost, that's not critically important, but other things might be.

Getting pretty late here, so I think I'm off for today, see ya! :wave:

**Comment by Globox1997** [comment]
I'll probably merge it but you don't have to make your own more work by doing this :)
See ya
