### ISSUE TITLE
[crash] MCDW weapons make the game crash

### ISSUE THREAD

**Issue by Kiryonn** [Globox1997/LevelZ#79]
I don't know yet if it's doing it for all weapons or just a few but at least 2 weapons makes the game crash when using levelZ

it's hard to tell if it's comming from levelZ or mcdw since the [crash report](https://github.com/Globox1997/LevelZ/files/7772034/crash-2021-12-24_01.46.59-client.txt) indicate that mcdw makes the game crash but i'm pretty sure it comes from levelZ.

also [here](https://github.com/chronosacaria/MCDungeonsWeapons/issues/69) is the issue made to chronosacari by someone else about something extremelly similar. let's not talk about the id of the issue x)

**Comment by xillenburg** [comment]
I have all of MCDungeons (weapons, armors, artifacts) mod on my world and not a single crash has occurred. I'm on 1.18 btw.

**Comment by Kiryonn** [comment]
i'm on 1.18.1

**Comment by xillenburg** [comment]
yeah im on 1.18.1. that's probably caused by other mods coz Im literally using a MCDW weapon rn (Void Touch Blade)

**Comment by finallion** [comment]
I'm getting the same crash log when using Levelz with The Graveyard. It crashes as soon as you use a weapon from The Graveyard in survival (not creative). The weapon extends the SwordItem class and Levelz tries to convert it to MiningToolItem causing the crash (https://pastebin.com/VvQLh6S6). 
It seems unlikely to be caused by the weapon - it is just extending the vanilla sword class, without adding extra stuff.

**Comment by Globox1997** [comment]
We'll see here: [https://github.com/chronosacaria/MCDungeonsWeapons/issues/69](https://github.com/chronosacaria/MCDungeonsWeapons/issues/69)

**Comment by MartinTornesello** [comment]
The problem lies within the mixin in LevelZ for calculating max damage (PlayerEntityMixin.java row 142): it is caused because the mod uses fabric tags to determine if a toolitem is a sword, axe, hoe or else. Since many other mods dont register their items tag to be bound inside those fabric tags, even though the dagger in graveyard is a SwordItem, it is not registered in the FabricToolItems.SWORDS tag.
`PlayerEntityMixin.java
Row 129 : if (playerEntity.getMainHandStack().isIn(FabricToolTags.SWORDS))` --> this returns false and the boolean isSword is not set to true. Because of this at line 142 the items is casted to MiningToolItem, which is not.
`Row 142: return zero ? 0 : original - ((MiningToolItem) playerEntity.getMainHandStack().getItem()).getAttackDamage();`

A simple solution although not the best it may be to use reflection since the method in SwordItem and MiningToolItem is named the same and returns in both cases a float -> then the method can be invoked onto the item. 

SO FROM 
`Line 139: if (isSword)
          return zero ? 0 : original - ((SwordItem) playerEntity.getMainHandStack().getItem()).getAttackDamage();
      else
          return zero ? 0 : original - ((MiningToolItem) playerEntity.getMainHandStack().getItem()).getAttackDamage();
  }`

TO 

`Line 139: try {
	Method getter = playerEntity.getMainHandStack().getItem().getClass().getDeclaredMethod("getAttackDamage");
        float attackDamage = (float) getter.invoke(playerEntity.getMainHandStack().getItem());
        return zero ? 0 : original - attackDamage;
} catch (NoSuchMethodException | SecurityException | IllegalAccessException | IllegalArgumentException | 
         InvocationTargetException e) {
          // TODO Auto-generated catch block
          e.printStackTrace();
}`

**Comment by Globox1997** [comment]
Thanks @MartinTornesello that is actually a very good idea, thanks for contributing

**Comment by Globox1997** [comment]
Changed with [https://github.com/Globox1997/LevelZ/commit/920c06effd6bf7e2f42f6fa73018cb7bb6afcabf](https://github.com/Globox1997/LevelZ/commit/920c06effd6bf7e2f42f6fa73018cb7bb6afcabf)

**Comment by Globox1997** [comment]
Looks like it doesn't work outside dev env:
`java.lang.NoSuchMethodException: net.minecraft.class_1829.getAttackDamage()`

**Comment by Globox1997** [comment]
Fixed it now with [https://github.com/Globox1997/LevelZ/commit/83b1519559f02606466b850ab62b9bb0e2283aac](https://github.com/Globox1997/LevelZ/commit/83b1519559f02606466b850ab62b9bb0e2283aac)
